version: "3"

services:
  devtools:
    container_name: devtools
    hostname: devtools
    image: ghcr.io/crhowell/codeplatoon/devtools:latest
    command: "tail -f /dev/null"
    networks:
      - cp_net
    ports:
      - "5990-5999:5990-5999"
    volumes:
      - "../challenges:/challenges"      
      - "../home/dev:/home/dev"
    environment:
      - PGHOST=postgres
      - PGPASSFILE=/home/db/dev/.pgpass
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 650M
        reservations:
          cpus: '1.0'
          memory: 500M
  db:
    container_name: postgres
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 300M
        reservations:
          cpus: '0.50'
          memory: 250M
    ports:
      - "5432"
    networks:
      - cp_net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  cp_net:
    driver: bridge
